### ISSUE TITLE
defaultHeader not applied

### ISSUE THREAD

**Issue by kboenke** [dmvstar/node-red-contrib-http-ntlm-req#2]
Creating a request without specifying msg.headers results in an error:

> TypeError: Cannot read property 'Content-Type' of undefined

Injecting a proper msg.headers['Content-Type'] prior will resolve this issue.

`[{"id":"a5dd6836.23b868","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"94318fa6.b3aa3","type":"inject","z":"a5dd6836.23b868","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":180,"wires":[["c391728c.6cfa3","7cd6907.4c3287"]]},{"id":"7cd6907.4c3287","type":"http-ntlm-req","z":"a5dd6836.23b868","name":"","url":"URL","method":0,"auth":"","x":730,"y":180,"wires":[["4ebc59c3.3cfe7"]]},{"id":"4ebc59c3.3cfe7","type":"debug","z":"a5dd6836.23b868","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":890,"y":180,"wires":[]},{"id":"c391728c.6cfa3","type":"change","z":"a5dd6836.23b868","name":"","rules":[{"t":"set","p":"headers","pt":"msg","to":"{\"Accept\":\"application/json;odata=nometadata\",\"Content-Type\":\"application/json;odata=nometadata\"}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":490,"y":240,"wires":[["7cd6907.4c3287"]]}]`

**Comment by Sayen** [comment]
Im still geting this Error: ReferenceError: err is not defined
Any Idea how to solve this?

**Comment by kboenke** [comment]
I do remember that this solver the problem for me. However, I no longer have it installed as it did not work out for me in the end (due to other reasons). Sorry. :(

**Comment by dmvstar** [comment]
Added to new refactoring version
